[versions]
gson = "2.10.1"
java-websocket = "1.5.6"
socket-io-client = "1.0.0"
engine-io-client = "1.0.0"
json = "20240303"
kotlin-stdlib = "1.9.20"
okio = "3.3.0"
okhttp = "4.12.0"
snakeyaml = "2.5"
jackson-annotations = "2.20"
jackson-databind = "2.20.1"
jackson-core = "2.20.1"
shadow = "9.2.2"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
java-websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "java-websocket" }
socket-io-client = { module = "io.socket:socket.io-client", version.ref = "socket-io-client" }
engine-io-client = { module = "io.socket:engine.io-client", version.ref = "engine-io-client" }
json = { module = "org.json:json", version.ref = "json" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-stdlib" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpSse = { module = "com.squareup.okhttp3:okhttp-sse", version.ref = "okhttp" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson-annotations" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-databind" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson-core" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }